"""Quantify adaptive- minus fixed-semantics intervention effects by thread."""

from __future__ import annotations

import argparse
import hashlib
import json
from pathlib import Path

import numpy as np
import pandas as pd


ROOT = Path(__file__).resolve().parents[1]
DEFAULT_INPUT = (
    ROOT
    / "artifacts"
    / "reviewer_validation"
    / "multithread_identification"
    / "thread_dispersion.csv"
)
DEFAULT_OUTPUT = (
    ROOT
    / "artifacts"
    / "reviewer_validation"
    / "adaptive_fixed_decomposition"
)


def _sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as stream:
        for chunk in iter(lambda: stream.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def _interval(values: np.ndarray) -> list[float]:
    return [float(np.quantile(values, 0.025)), float(np.quantile(values, 0.975))]


def analyze(
    input_path: Path,
    output_dir: Path,
    *,
    bootstrap_samples: int = 10_000,
    seed: int = 30371,
) -> dict[str, object]:
    frame = pd.read_csv(input_path)
    required = {"community", "post_id", "live_mean_effect", "frozen_mean_effect"}
    missing = required.difference(frame.columns)
    if missing:
        raise ValueError(f"missing columns: {sorted(missing)}")
    if frame[["community", "post_id"]].duplicated().any():
        raise ValueError("thread identifiers must be unique")

    frame = frame.copy()
    frame["adaptive_minus_fixed"] = frame["live_mean_effect"] - frame["frozen_mean_effect"]
    frame["absolute_gap"] = frame["adaptive_minus_fixed"].abs()
    frame["direction_reversal"] = (
        frame["live_mean_effect"] * frame["frozen_mean_effect"] < 0
    )

    rng = np.random.default_rng(seed)
    indices = rng.integers(0, len(frame), size=(bootstrap_samples, len(frame)))
    gaps = frame["adaptive_minus_fixed"].to_numpy(dtype=float)[indices]
    mean_draws = gaps.mean(axis=1)
    median_draws = np.median(gaps, axis=1)
    median_abs_draws = np.median(np.abs(gaps), axis=1)

    summary = {
        "status": "complete",
        "estimand": "thread-level adaptive-semantic minus fixed-semantics mean log-volume effect",
        "threads": int(len(frame)),
        "paired_seeds_per_thread": int(frame["paired_seeds"].min())
        if "paired_seeds" in frame.columns
        else None,
        "mean_gap": float(frame["adaptive_minus_fixed"].mean()),
        "mean_gap_ci": _interval(mean_draws),
        "median_gap": float(frame["adaptive_minus_fixed"].median()),
        "median_gap_ci": _interval(median_draws),
        "median_absolute_gap": float(frame["absolute_gap"].median()),
        "median_absolute_gap_ci": _interval(median_abs_draws),
        "adaptive_mean_effect": float(frame["live_mean_effect"].mean()),
        "fixed_mean_effect": float(frame["frozen_mean_effect"].mean()),
        "direction_reversals": int(frame["direction_reversal"].sum()),
        "bootstrap_samples": bootstrap_samples,
        "bootstrap_unit": "thread",
        "input_sha256": _sha256(input_path),
    }

    output_dir.mkdir(parents=True, exist_ok=True)
    frame.to_csv(output_dir / "thread_effect_decomposition.csv", index=False)
    (output_dir / "adaptive_fixed_decomposition.json").write_text(
        json.dumps(summary, indent=2, sort_keys=True), encoding="utf-8"
    )
    macros = [
        "% Auto-generated by analyze_adaptive_fixed_decomposition.py.",
        f"\\newcommand{{\\AdaptiveFixedThreads}}{{{summary['threads']}}}",
        f"\\newcommand{{\\AdaptiveFixedMeanGap}}{{{summary['mean_gap']:.3f}}}",
        f"\\newcommand{{\\AdaptiveFixedMeanGapLow}}{{{summary['mean_gap_ci'][0]:.3f}}}",
        f"\\newcommand{{\\AdaptiveFixedMeanGapHigh}}{{{summary['mean_gap_ci'][1]:.3f}}}",
        f"\\newcommand{{\\AdaptiveFixedMedianAbsGap}}{{{summary['median_absolute_gap']:.3f}}}",
        f"\\newcommand{{\\AdaptiveFixedMedianAbsGapLow}}{{{summary['median_absolute_gap_ci'][0]:.3f}}}",
        f"\\newcommand{{\\AdaptiveFixedMedianAbsGapHigh}}{{{summary['median_absolute_gap_ci'][1]:.3f}}}",
        f"\\newcommand{{\\AdaptiveFixedReversals}}{{{summary['direction_reversals']}}}",
    ]
    (output_dir / "adaptive_fixed_decomposition_macros.tex").write_text(
        "\n".join(macros) + "\n", encoding="utf-8"
    )
    return summary


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--input", type=Path, default=DEFAULT_INPUT)
    parser.add_argument("--output-dir", type=Path, default=DEFAULT_OUTPUT)
    parser.add_argument("--bootstrap-samples", type=int, default=10_000)
    parser.add_argument("--seed", type=int, default=30371)
    args = parser.parse_args()
    result = analyze(
        args.input,
        args.output_dir,
        bootstrap_samples=args.bootstrap_samples,
        seed=args.seed,
    )
    print(json.dumps(result, indent=2, sort_keys=True))


if __name__ == "__main__":
    main()
