"""Analyze blinded semantic ratings with item and assignment clustering.

The primary acceptability rule treats a rendered reply as minimally executable
when both relevance and coherence are at least 3/5 and no obvious mismatch is
reported.  The stricter 4/5 rule is retained as a secondary stress test.
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path

import numpy as np
import pandas as pd
import statsmodels.api as sm
from statsmodels.stats.sandwich_covariance import cov_cluster_2groups


ROOT = Path(__file__).resolve().parents[1]
DEFAULT_INPUT = (
    ROOT
    / "artifacts"
    / "reviewer_validation"
    / "semantic_parent_audit"
    / "human_results_20260825"
    / "RATINGS_PAIRED_DECODED.csv"
)
DEFAULT_OUTPUT = DEFAULT_INPUT.parent / "two_way_cluster_analysis"


def _clustered_mean(values: pd.Series, item: pd.Series, assignment: pd.Series) -> dict[str, float]:
    y = values.astype(float).to_numpy()
    design = np.ones((len(y), 1), dtype=float)
    fit = sm.OLS(y, design).fit()
    item_codes = pd.factorize(item, sort=True)[0]
    assignment_codes = pd.factorize(assignment, sort=True)[0]
    covariance = cov_cluster_2groups(fit, item_codes, assignment_codes)[0]
    estimate = float(y.mean())
    standard_error = float(np.sqrt(covariance[0, 0]))
    return {
        "estimate": estimate,
        "standard_error": standard_error,
        "ci_low": estimate - 1.96 * standard_error,
        "ci_high": estimate + 1.96 * standard_error,
    }


def _clustered_slope(
    outcome: pd.Series,
    indicator: pd.Series,
    item: pd.Series,
    assignment: pd.Series,
) -> dict[str, float]:
    y = outcome.astype(float).to_numpy()
    design = sm.add_constant(indicator.astype(float).to_numpy())
    fit = sm.OLS(y, design).fit()
    item_codes = pd.factorize(item, sort=True)[0]
    assignment_codes = pd.factorize(assignment, sort=True)[0]
    covariance = cov_cluster_2groups(fit, item_codes, assignment_codes)[0]
    estimate = float(fit.params[1])
    standard_error = float(np.sqrt(covariance[1, 1]))
    return {
        "estimate": estimate,
        "standard_error": standard_error,
        "ci_low": estimate - 1.96 * standard_error,
        "ci_high": estimate + 1.96 * standard_error,
    }


def _add_validity_columns(ratings: pd.DataFrame) -> pd.DataFrame:
    ratings = ratings.copy()
    for source in ("frame", "verbatim"):
        ratings[f"{source}_acceptable"] = (
            (ratings[f"{source}_relevance"] >= 3)
            & (ratings[f"{source}_coherence"] >= 3)
            & (ratings[f"{source}_mismatch"] == 0)
        ).astype(int)
        ratings[f"{source}_strict"] = (
            (ratings[f"{source}_relevance"] >= 4)
            & (ratings[f"{source}_coherence"] >= 4)
            & (ratings[f"{source}_mismatch"] == 0)
        ).astype(int)
    return ratings


def _percent(value: float) -> float:
    return round(100.0 * value, 1)


def _write_tex(summary: dict[str, object], output_dir: Path) -> None:
    acceptable = summary["acceptable"]
    metrics = summary["paired_differences"]
    macros = "\n".join(
        [
            "% Auto-generated by analyze_human_semantic_acceptability.py.",
            f"\\newcommand{{\\HumanAcceptableFramePct}}{{{_percent(acceptable['frame']['estimate']):.1f}}}",
            f"\\newcommand{{\\HumanAcceptableFrameLow}}{{{_percent(acceptable['frame']['ci_low']):.1f}}}",
            f"\\newcommand{{\\HumanAcceptableFrameHigh}}{{{_percent(acceptable['frame']['ci_high']):.1f}}}",
            f"\\newcommand{{\\HumanAcceptableVerbatimPct}}{{{_percent(acceptable['verbatim']['estimate']):.1f}}}",
            f"\\newcommand{{\\HumanAcceptableVerbatimLow}}{{{_percent(acceptable['verbatim']['ci_low']):.1f}}}",
            f"\\newcommand{{\\HumanAcceptableVerbatimHigh}}{{{_percent(acceptable['verbatim']['ci_high']):.1f}}}",
            f"\\newcommand{{\\HumanAcceptableDifferencePP}}{{{_percent(metrics['acceptable']['estimate']):+.1f}}}",
            f"\\newcommand{{\\HumanAcceptableDifferenceLowPP}}{{{_percent(metrics['acceptable']['ci_low']):+.1f}}}",
            f"\\newcommand{{\\HumanAcceptableDifferenceHighPP}}{{{_percent(metrics['acceptable']['ci_high']):+.1f}}}",
            f"\\newcommand{{\\HumanRelevanceTwoWayLow}}{{{metrics['relevance']['ci_low']:+.2f}}}",
            f"\\newcommand{{\\HumanRelevanceTwoWayHigh}}{{{metrics['relevance']['ci_high']:+.2f}}}",
            f"\\newcommand{{\\HumanCoherenceTwoWayLow}}{{{metrics['coherence']['ci_low']:+.2f}}}",
            f"\\newcommand{{\\HumanCoherenceTwoWayHigh}}{{{metrics['coherence']['ci_high']:+.2f}}}",
            f"\\newcommand{{\\HumanValidTwoWayLowPP}}{{{_percent(metrics['strict']['ci_low']):+.1f}}}",
            f"\\newcommand{{\\HumanValidTwoWayHighPP}}{{{_percent(metrics['strict']['ci_high']):+.1f}}}",
            f"\\newcommand{{\\HumanMismatchTwoWayLowPP}}{{{_percent(metrics['mismatch']['ci_low']):+.1f}}}",
            f"\\newcommand{{\\HumanMismatchTwoWayHighPP}}{{{_percent(metrics['mismatch']['ci_high']):+.1f}}}",
            f"\\newcommand{{\\HumanAcceptableCoreDifferencePP}}{{{_percent(summary['acceptability_balance']['conflict_minus_baseline']['estimate']):+.1f}}}",
            f"\\newcommand{{\\HumanAcceptableCoreDifferenceLowPP}}{{{_percent(summary['acceptability_balance']['conflict_minus_baseline']['ci_low']):+.1f}}}",
            f"\\newcommand{{\\HumanAcceptableCoreDifferenceHighPP}}{{{_percent(summary['acceptability_balance']['conflict_minus_baseline']['ci_high']):+.1f}}}",
            f"\\newcommand{{\\HumanAcceptableRankingDifferencePP}}{{{_percent(summary['acceptability_balance']['controversial_minus_best']['estimate']):+.1f}}}",
            f"\\newcommand{{\\HumanAcceptableRankingDifferenceLowPP}}{{{_percent(summary['acceptability_balance']['controversial_minus_best']['ci_low']):+.1f}}}",
            f"\\newcommand{{\\HumanAcceptableRankingDifferenceHighPP}}{{{_percent(summary['acceptability_balance']['controversial_minus_best']['ci_high']):+.1f}}}",
            f"\\newcommand{{\\HumanAcceptableDeepDifferencePP}}{{{_percent(summary['acceptability_balance']['deep_minus_shallow']['estimate']):+.1f}}}",
            f"\\newcommand{{\\HumanAcceptableDeepDifferenceLowPP}}{{{_percent(summary['acceptability_balance']['deep_minus_shallow']['ci_low']):+.1f}}}",
            f"\\newcommand{{\\HumanAcceptableDeepDifferenceHighPP}}{{{_percent(summary['acceptability_balance']['deep_minus_shallow']['ci_high']):+.1f}}}",
            f"\\newcommand{{\\HumanAcceptableRootDifferencePP}}{{{_percent(summary['acceptability_balance']['root_minus_shallow']['estimate']):+.1f}}}",
            f"\\newcommand{{\\HumanAcceptableRootDifferenceLowPP}}{{{_percent(summary['acceptability_balance']['root_minus_shallow']['ci_low']):+.1f}}}",
            f"\\newcommand{{\\HumanAcceptableRootDifferenceHighPP}}{{{_percent(summary['acceptability_balance']['root_minus_shallow']['ci_high']):+.1f}}}",
            "",
        ]
    )
    (output_dir / "human_semantic_acceptability_macros.tex").write_text(macros, encoding="utf-8")

    table = r"""\setlength{\tabcolsep}{2.8pt}
\begin{tabular}{lrrr}
\toprule
Metric & Frame & Verbatim & $\Delta$ [95\% CI] \\
\midrule
Acceptable (\%) & \HumanAcceptableFramePct{} & \HumanAcceptableVerbatimPct{} &
\HumanAcceptableDifferencePP{} [\HumanAcceptableDifferenceLowPP{}, \HumanAcceptableDifferenceHighPP{}] pp \\
Relevance (1--5) & \HumanFrameRelevance{} & \HumanVerbatimRelevance{} &
\HumanRelevanceDifference{} [\HumanRelevanceTwoWayLow{}, \HumanRelevanceTwoWayHigh{}] \\
Coherence (1--5) & \HumanFrameCoherence{} & \HumanVerbatimCoherence{} &
\HumanCoherenceDifference{} [\HumanCoherenceTwoWayLow{}, \HumanCoherenceTwoWayHigh{}] \\
Strict valid (\%) & \HumanFrameValidPct{} & \HumanVerbatimValidPct{} &
\HumanValidDifferencePP{} [\HumanValidTwoWayLowPP{}, \HumanValidTwoWayHighPP{}] pp \\
Mismatch (\%) & \HumanFrameMismatchPct{} & \HumanVerbatimMismatchPct{} &
\HumanMismatchDifferencePP{} [\HumanMismatchTwoWayLowPP{}, \HumanMismatchTwoWayHighPP{}] pp \\
\bottomrule
\end{tabular}
"""
    (output_dir / "table_human_semantic_acceptability.tex").write_text(table, encoding="utf-8")


def analyze(input_path: Path, output_dir: Path) -> dict[str, object]:
    ratings = _add_validity_columns(pd.read_csv(input_path))
    required = {"item_id", "assignment_id"}
    missing = required.difference(ratings.columns)
    if missing:
        raise ValueError(f"missing required columns: {sorted(missing)}")

    summary: dict[str, object] = {
        "ratings": int(len(ratings)),
        "items": int(ratings["item_id"].nunique()),
        "anonymous_assignments": int(ratings["assignment_id"].nunique()),
        "interval_method": "OLS intercept with two-way item and assignment cluster-robust covariance",
    }

    summary["acceptable"] = {
        source: _clustered_mean(
            ratings[f"{source}_acceptable"], ratings["item_id"], ratings["assignment_id"]
        )
        for source in ("frame", "verbatim")
    }
    summary["strict"] = {
        source: _clustered_mean(
            ratings[f"{source}_strict"], ratings["item_id"], ratings["assignment_id"]
        )
        for source in ("frame", "verbatim")
    }

    differences = {
        "acceptable": ratings["frame_acceptable"] - ratings["verbatim_acceptable"],
        "strict": ratings["frame_strict"] - ratings["verbatim_strict"],
        "relevance": ratings["frame_relevance"] - ratings["verbatim_relevance"],
        "coherence": ratings["frame_coherence"] - ratings["verbatim_coherence"],
        "mismatch": ratings["frame_mismatch"] - ratings["verbatim_mismatch"],
    }
    summary["paired_differences"] = {
        name: _clustered_mean(values, ratings["item_id"], ratings["assignment_id"])
        for name, values in differences.items()
    }

    frame_acceptable = ratings["frame_acceptable"]
    balance: dict[str, dict[str, float]] = {}
    for name, indicator in (
        ("conflict_minus_baseline", ratings["core"].eq("toxic")),
        ("controversial_minus_best", ratings["ranking"].eq("controversial")),
    ):
        balance[name] = _clustered_slope(
            frame_acceptable,
            indicator,
            ratings["item_id"],
            ratings["assignment_id"],
        )
    for name, level in (("deep_minus_shallow", "deep_reply"), ("root_minus_shallow", "root_reply")):
        subset = ratings[ratings["depth_bin"].isin(["shallow_reply", level])]
        balance[name] = _clustered_slope(
            subset["frame_acceptable"],
            subset["depth_bin"].eq(level),
            subset["item_id"],
            subset["assignment_id"],
        )
    summary["acceptability_balance"] = balance

    strata = []
    for column in ("depth_bin", "core", "ranking", "community", "polarity"):
        for level, group in ratings.groupby(column, dropna=False):
            strata.append(
                {
                    "stratum": column,
                    "level": str(level),
                    "ratings": int(len(group)),
                    "frame_acceptable": float(group["frame_acceptable"].mean()),
                    "verbatim_acceptable": float(group["verbatim_acceptable"].mean()),
                }
            )

    output_dir.mkdir(parents=True, exist_ok=True)
    (output_dir / "summary.json").write_text(
        json.dumps(summary, indent=2, sort_keys=True), encoding="utf-8"
    )
    pd.DataFrame(strata).to_csv(output_dir / "stratified_acceptability.csv", index=False)
    _write_tex(summary, output_dir)
    return summary


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--input", type=Path, default=DEFAULT_INPUT)
    parser.add_argument("--output-dir", type=Path, default=DEFAULT_OUTPUT)
    args = parser.parse_args()
    summary = analyze(args.input, args.output_dir)
    acceptable = summary["acceptable"]
    difference = summary["paired_differences"]["acceptable"]
    print(
        "acceptable: "
        f"frame={100 * acceptable['frame']['estimate']:.1f}%, "
        f"verbatim={100 * acceptable['verbatim']['estimate']:.1f}%, "
        f"difference={100 * difference['estimate']:+.1f} pp "
        f"[{100 * difference['ci_low']:+.1f}, {100 * difference['ci_high']:+.1f}]"
    )


if __name__ == "__main__":
    main()
