"""Create manuscript artifacts from the completed Qref decomposition."""

from __future__ import annotations

import argparse
import json
import math
from pathlib import Path

import pandas as pd


ROOT = Path(__file__).resolve().parents[1]


def fmt(value: float, digits: int = 3) -> str:
    return f"{value:.{digits}f}"


def write_table(frame: pd.DataFrame, path: Path) -> None:
    content = frame[frame["effect"] == "content_only"].set_index("family")
    mapping = frame[frame["effect"] == "mapping_only"].set_index("family")
    lines = [
        r"\begin{tabular}{lrrrr}",
        r"\toprule",
        r"Family & Catalog-only $\Delta\log$ RoR & Map RoR factor [95\% CI] & Catalog-only $\Delta$ depth & Map $\Delta$ depth [95\% CI] \\",
        r"\midrule",
    ]
    for family in sorted(mapping.index):
        c = content.loc[family]
        m = mapping.loc[family]
        lines.append(
            f"{family.title()} & {fmt(c.log_volume_difference)} & "
            f"{fmt(math.exp(m.log_volume_difference))} "
            f"[{fmt(math.exp(m.log_volume_ci_low))}, {fmt(math.exp(m.log_volume_ci_high))}] & "
            f"{fmt(c.depth_difference)} & {fmt(m.depth_difference)} "
            f"[{fmt(m.depth_ci_low)}, {fmt(m.depth_ci_high)}] "
            + r"\\"
        )
    lines.extend([r"\bottomrule", r"\end{tabular}"])
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def write_macros(frame: pd.DataFrame, path: Path) -> None:
    content = frame[frame["effect"] == "content_only"]
    mapping = frame[frame["effect"] == "mapping_only"].copy()
    mapping["volume_factor"] = mapping["log_volume_difference"].map(math.exp)
    nonadditive = frame[frame["effect"] == "nonadditive"]
    lines = [
        "% Auto-generated by scripts/summarize_qref_decomposition.py.",
        rf"\newcommand{{\QRefDecompositionFamilies}}{{{mapping['family'].nunique()}}}",
        rf"\newcommand{{\QRefContentMaxLogVolume}}{{{content['log_volume_difference'].abs().max():.3f}}}",
        rf"\newcommand{{\QRefContentMaxDepth}}{{{content['depth_difference'].abs().max():.3f}}}",
        rf"\newcommand{{\QRefMapVolumeFactorMin}}{{{mapping['volume_factor'].min():.3f}}}",
        rf"\newcommand{{\QRefMapVolumeFactorMax}}{{{mapping['volume_factor'].max():.3f}}}",
        rf"\newcommand{{\QRefMapDepthMin}}{{{mapping['depth_difference'].min():.3f}}}",
        rf"\newcommand{{\QRefMapDepthMax}}{{{mapping['depth_difference'].max():.3f}}}",
        rf"\newcommand{{\QRefNonadditiveMaxLogVolume}}{{{nonadditive['log_volume_difference'].abs().max():.3f}}}",
        rf"\newcommand{{\QRefNonadditiveMaxDepth}}{{{nonadditive['depth_difference'].abs().max():.3f}}}",
    ]
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--input",
        type=Path,
        default=ROOT / "artifacts" / "reviewer_validation" / "qref_decomposition_20260908",
    )
    parser.add_argument(
        "--generated",
        type=Path,
        default=ROOT
        / "manuscript"
        / "iclr2027_overleaf_package_review_fixed_20260908"
        / "generated",
    )
    args = parser.parse_args()
    frame = pd.read_csv(args.input / "decomposition.csv")
    required = {
        (family, effect)
        for family in ("openai", "deepseek", "qwen")
        for effect in ("content_only", "mapping_only", "nonadditive")
    }
    observed = set(zip(frame["family"], frame["effect"], strict=True))
    if observed != required:
        raise ValueError(f"Unexpected decomposition cells: {sorted(observed)}")
    args.generated.mkdir(parents=True, exist_ok=True)
    write_table(frame, args.generated / "table_qref_decomposition.tex")
    write_macros(frame, args.generated / "qref_decomposition_macros.tex")
    summary = {
        "families": sorted(frame["family"].unique()),
        "content_only_max_abs_log_volume": float(
            frame.loc[frame.effect == "content_only", "log_volume_difference"].abs().max()
        ),
        "content_only_max_abs_depth": float(
            frame.loc[frame.effect == "content_only", "depth_difference"].abs().max()
        ),
        "interpretation": (
            "Surface-catalog substitution is a deterministic transition-kernel check; "
            "family-specific operational coordinate maps define the scientific sensitivity."
        ),
    }
    (args.input / "manuscript_summary.json").write_text(
        json.dumps(summary, indent=2, sort_keys=True), encoding="utf-8"
    )
    print(json.dumps(summary, indent=2, sort_keys=True))


if __name__ == "__main__":
    main()
